2018-04-08 14:08:04,923 ERROR: Exception on /index [GET] [in /home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py: 1560]
Traceback (most recent call last):
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ari/Documents/LastChance/microblog/app/routes.py", line 80, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ari/Documents/LastChance/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/wtf.html
2018-04-08 14:13:13,358 INFO: Microblog startup [in /home/ari/Documents/LastChance/microblog/app/__init__.py: 49]
2018-04-08 14:13:18,188 ERROR: Exception on /index [GET] [in /home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py: 1560]
Traceback (most recent call last):
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ari/Documents/LastChance/microblog/app/routes.py", line 80, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ari/Documents/LastChance/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/wtf.html
2018-04-08 14:13:21,606 ERROR: Exception on /index [GET] [in /home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py: 1560]
Traceback (most recent call last):
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/ari/Documents/LastChance/microblog/app/routes.py", line 80, in index
    return render_template('index.html', title='Home Page', form=form, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/ari/Documents/LastChance/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/home/ari/Documents/LastChance/microblog/mb_venv/lib/python3.5/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/wtf.html
